/*


*/
CREATE TABLE IF NOT EXISTS USER(
	USER_PR INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_ARMYNUMBER CHAR(100) NOT NULL,
	USER_NAME CHAR(100) NOT NULL,
	PASSWORD CHAR(100) NOT NULL,
    USER_DISCHARGEDATE DATETIME,
    UPDATADATE DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS PHONE(
    PHONE_PR INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_UNIQUENUM INTGER NOT NULL,
    PHONE_IP CHAR(100) NOT NULL,
    CONSTRAINT UNIQUENUM FOREIGN KEY(USER_UNIQUENUM)
    REFERENCES USER(USER_PR)
);

CREATE TABLE IF NOT EXISTS IOT_CASE(
    CASE_PR INTEGER PRIMARY KEY AUTOINCREMENT,
    
);