CREATE TABLE IF NOT EXISTS USER(
	USER_PR INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_ARMYNUMBER CHAR(100) NOT NULL,
	USER_NAME CHAR(100) NOT NULL,
	PASSWORD CHAR(100) NOT NULL,
    USER_DISCHARGEDATE DATETIME,
    UPDATEDATE DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS PHONE(
    PHONE_PR INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_UNIQUENUM INTEGER NOT NULL,
    PHONE_IP CHAR(100) NOT NULL,
    IS_LOCK INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT UNIQUENUM FOREIGN KEY(USER_UNIQUENUM)
    REFERENCES USER(USER_PR)
);

CREATE TABLE IF NOT EXISTS PHONECASE(
    PHONECASE_PR INTEGER PRIMARY KEY AUTOINCREMENT,
    IS_LOCK INTEGER NOT NULL,
    PHONE1_ID INTEGER,
    PHONE2_ID INTEGER,
    PHONE3_ID INTEGER,
    PHONE4_ID INTEGER,
    CONSTRAINT PHONESTRAINT1 FOREIGN KEY(PHONE1_ID)
    REFERENCES PHONE(PHONE_PR),
    CONSTRAINT PHONESTRAINT1 FOREIGN KEY(PHONE2_ID)
    REFERENCES PHONE(PHONE_PR),
    CONSTRAINT PHONESTRAINT1 FOREIGN KEY(PHONE3_ID)
    REFERENCES PHONE(PHONE_PR),
    CONSTRAINT PHONESTRAINT1 FOREIGN KEY(PHONE4_ID)
    REFERENCES PHONE(PHONE_PR)
);

CREATE TABLE IF NOT EXISTS LOCKMANAGE(
    LOCKMANAGE_PR INTEGER PRIMARY KEY AUTOINCREMENT,
    PHONE_UNIQUENUM INTEGER NOT NULL,
    MANAGETIME DATETIME NOT NULL,
    IS_LOCK INTEGER NOT NULL,
    CONSTRAINT MANAGESTRAINT1 FOREIGN KEY(PHONE_UNIQUENUM)
    REFERENCES PHONE(PHONE_PR)
);

