/*
DELETE FROM USER;


UPDATE SQLITE_SEQUENCE SET SEQ=0 WHERE NAME = 'USER';
UPDATE SQLITE_SEQUENCE SET SEQ=0 WHERE NAME = 'PHONE';


INSERT INTO USER (USER_ARMYNUMBER, USER_NAME, PASSWORD, USER_DISCHARGEDATE, UPDATEDATE)
VALUES('19-76073001','김영호','password',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO PHONE(USER_UNIQUENUM, PHONE_IP)
VALUES(1,'127.0.0.1');
INSERT INTO PHONE(USER_UNIQUENUM, PHONE_IP)
VALUES(1,'127.0.0.2');
INSERT INTO PHONE(USER_UNIQUENUM, PHONE_IP)
VALUES(1,'127.0.0.3');
INSERT INTO PHONE(USER_UNIQUENUM, PHONE_IP)
VALUES(1,'127.0.0.4');

INSERT INTO PHONECASE(IS_LOCK, PHONE1_ID,PHONE2_ID,PHONE3_ID,PHONE4_ID)
VALUES(0,1,2,3,4);

INSERT INTO LOCKMANAGE (PHONE_UNIQUENUM,MANAGETIME, IS_LOCK)
VALUES(1,CURRENT_TIMESTAMP,1);

*/
SELECT * FROM PHONE;
SELECT * FROM PHONECASE;
SELECT * FROM LOCKMANAGE;